version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://eyoba:Eyoba21@mernapp.v9glrpn.mongodb.net/?retryWrites=true&w=majority&appName=MERNapp
      - PORT=5000
    volumes:
      - .:/usr/src/app
